### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by TomHunter1** [ColonelJ/tronscan-transfers-downloader#1]
Hi, 

Using v1.17.3, when creating a test CSV file, the following error appears at execution. 

`Writing to file test.csv...
(node:5313) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'open' of undefined
    at main (ANN/index.js:150:36)
    at Object.<anonymous> (ANN/index.js:201:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

(node:5313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:5313) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by ColonelJ** [comment]
Hi the problem you are experiencing is because you are running a too old version of Node.js.  Please upgrade the Node.js on your system to at least version 10 (which includes the new fsPromises API).  You can get it from their website.
